const React = require('react');
const DOM = React.DOM;

var FormInputWithLabel = React.createClass({
  getDefaultProps() {
    return {
      elementType: "input",
      inputType: "text",
      displayName: "FormInputWithLabel"
    };
  },
  render() {
    return DOM.div({
      className: "form-group",
      key: this.props.key
    },
      DOM.label({
        htmlFor: this.props.id,
        className: "col-lg-2 control-label",
        key: this.props.key
      }, this.props.labelText),
    DOM.div({
      className: "col-lg-10",
      key: this.props.key
    },"yolo",
      DOM[this.props.elementType]({
        className: "form-control",
        placeholder: this.props.placeholder,
        id: this.props.id,
        type: "text",
        value: this.props.value,
        onChange: this.props.onChange,
        key: this.props.key,
        type: this.tagType()
    })));
  },
  tagType() {
    return {
      "input": this.props.inputType,
      "textarea": null
    }[this.props.elementType];
  }
});

module.exports = React.createFactory(FormInputWithLabel);

// ---
// generated by coffee-script 1.9.2
